### ISSUE TITLE
Ampliar registro de entidades

### ISSUE THREAD

**Issue by xavier506** [LatamLink/latamlink.io#130]
Para registrarse como una entidad es necesario que el comite permisionador obtenga los siguientes datos de la entidad que desea registrarse

- entity_name (nombre de cuenta de la entidad)
- entity_type (partner o non-partner)
- pub_key (llave publica para cuenta de la nueva entidad)

![image](https://user-images.githubusercontent.com/5632966/116337685-bc8a1b80-a797-11eb-9545-6b5bab2ffa0c.png)

**Comment by AngeloCG97** [comment]
Cualquier usuario podría tener acceso a este formulario? o solo alguno que forme parte del comité?

**Comment by xavier506** [comment]
> Cualquier usuario podría tener acceso a este formulario? o solo alguno que forme parte del comité?

solo el comite , pero los usuarios deben de pasarle los datos al comite para que puedan registrarlo

**Comment by AngeloCG97** [comment]
Ok de acuerdo, gracias por el dato.
