### ISSUE TITLE
Como configuro mi billietera para lacchain?

### ISSUE THREAD

**Issue by xavier506** [LatamLink/latamlink.io#132]
Una vez obtenida la cuenta necesito saber como configurar mi billetera para lacchain 

- Anchor Wallet
- Otros wallets

**Comment by AngeloCG97** [comment]
En este enlace se habla un poco sobre este tema, es a esto a lo que se refiere este issue? 

https://es.latamlink.io/docs/guias/llaves-privadas

**Comment by xavier506** [comment]
ya has configurado una cuenta de lacchain en el anchor wallet? 

hay que configurar varias cosas para que funcione , no solo importar la llave privadas

**Comment by AngeloCG97** [comment]
Comprendo, voy a investigar sobre el proceso para documentarlo.
