### ISSUE TITLE
Guía para instalación de Nodos

### ISSUE THREAD

**Issue by xavier506** [LatamLink/latamlink.io#37]
- [ ] Guía para la instalación de nodos productores de bloques
- [ ] Guía para la instalación de nodos Validator / Boot / Writer / Observer 

http://latamlink.io/docs/en/instalacion-nodos

Referencia : 

https://github.com/LatamLink/eosio-testnet

**Comment by xavier506** [comment]
@JeanVegaD  @AngeloCG97 

Una vez que se registra la cuenta de un entity , ya sea partner o non-partner, este puede registrar nodos.

Para registrar nodos puede autenticarse en el dashboard y llenar el formulario para el tipo de nodo que desea registrar 

![image](https://user-images.githubusercontent.com/5632966/116336493-e2aebc00-a795-11eb-8666-61c2d40f8a25.png)

Los tipos de nodos depende del tipo de entidad 

los partners pueden desplegar cualquier tipo de nodo mientras que los non partners solo escritores y observadores.

una vez que la entidad esta autenticada en el dashboard tambien puede bajar un archivo de configuración de muestra para su tipo de nodo 


![image](https://user-images.githubusercontent.com/5632966/116336639-26a1c100-a796-11eb-80d0-3480c34f57de.png)

**Comment by xavier506** [comment]
tambien hay una funcion donde entidades pueden borrar nodos

![image](https://user-images.githubusercontent.com/5632966/116338986-e3e1e800-a799-11eb-978c-85375e79f50c.png)

**Comment by AngeloCG97** [comment]
Thanks by the content
